import { replaceFor } from "@/utils/MU";

type StreamServiceDef = {
  name: string;
  alias: string[];
  active: boolean;
  logo: string;
};

export function getStreamService(value: string) {
  if (!value) return undefined;
  const keyValue = replaceFor(value.toLowerCase(), " ", "");
  return StreamServices.find((srvc) => srvc.alias.includes(keyValue));
}

export const StreamServices: StreamServiceDef[] = [
  {
    alias: ["a&e"],
    name: "A&E",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/ae_100px.png",
  },
  {
    alias: ["amc"],
    name: "AMC",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/amc_100px.png",
  },
  {
    alias: ["amc+"],
    name: "AMC+",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/378_autogenerated.png",
  },
  {
    alias: ["bbcamerica"],
    name: "BBC America",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/bbc_america_100px.png",
  },
  {
    alias: ["britbox"],
    name: "Britbox",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/britbox_100px.png",
  },
  {
    alias: ["curiositystream"],
    name: "Curiosity Stream",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/421_autogenerated.png",
  },
  {
    alias: ["discovery+"],
    name: "Discovery+",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/445_autogenerated.png",
  },
  {
    alias: ["fx"],
    name: "FX",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/fx_100px.png",
  },
  {
    alias: ["fandor"],
    name: "Fandor",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/fandor_100px.png",
  },
  {
    alias: ["historyvault", "historyvault(viaamazonprime)"],
    name: "HISTORY Vault",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/history_vault_100px.png",
  },
  {
    alias: ["hallmarkmoviesnow"],
    name: "Hallmark Movies Now",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/hallmark_movies_now_100px.png",
  },
  {
    alias: ["hallmarkchanneleverywhere"],
    name: "Hallmark Channel Everywhere",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/hallmark_100px.png",
  },
  {
    alias: ["smithsonianchannel"],
    name: "Smithsonian Channel",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/smithsonian_100px.png",
  },
  {
    alias: ["syfy"],
    name: "Syfy",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/syfy_100px.png",
  },
  {
    alias: ["tbs"],
    name: "TBS",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/tbs_100px.png",
  },
  {
    alias: ["thehistorychannel"],
    name: "The History Channel",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/history_100px.png",
  },
  {
    alias: ["itunes"],
    name: "iTunes",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/apple_100px.png",
  },
  {
    alias: ["abc_tveverywhere", "abc"],
    name: "ABC",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/abc_100px.png",
  },
  {
    alias: ["amazon_prime", "amazonprime"],
    name: "Amazon Prime",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/prime_video_100px.png",
  },
  {
    alias: ["apple_tv_plus", "appletv+", "apple_tv", "appletv"],
    name: "Apple TV+",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/appleTvPlus_100px.png",
  },
  {
    alias: ["comedy_central_tveverywhere", "comedycentral"],
    name: "Comedy Central",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/cc_100px.png",
  },
  {
    alias: ["disney_plus", "disney+"],
    name: "Disney+",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/disneyPlus_100px.png",
  },
  {
    alias: ["fox_tveverywhere", "fox"],
    name: "Fox",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/fox_100px.png",
  },
  {
    alias: ["hbo_max", "hbomax"],
    name: "HBO Max",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/hbomax_100px.png",
  },
  {
    alias: ["hulu"],
    name: "Hulu",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/hulu_100px.png",
  },
  {
    alias: ["netflix"],
    name: "Netflix",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/netflix_100px.png",
  },
  {
    alias: ["paramount_plus", "paramount+"],
    name: "Paramount+",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/paramountPlus_100px.png",
  },
  {
    alias: ["peacock", "peacockpremium"],
    name: "Peacock Premium",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/peacock_100px.png",
  },
  {
    alias: ["showtime"],
    name: "Showtime",
    active: true,
    logo: "https://cdn.watchmode.com/provider_logos/showtime_100px.png",
  },
];
